
#include "TROOT.h"
#include "TFile.h"
#include "TSystem.h"
#include "TH1.h"

void comparoldnew()
{ 
  gROOT->SetStyle("Plain");
  gStyle->SetOptTitle(0);
// Create a new canvas.
  c1 = new TCanvas("c1");
  //  c1->SetFillColor(42);
  //c1->GetFrame()->SetFillColor(21);
  c1->GetFrame()->SetBorderSize(6);
  c1->GetFrame()->SetBorderMode(-1);

  TFile *Old = TFile::Open("ZmumuAnalyzer_175.root","READ");
  TFile *New = TFile::Open("ZmumuAnalyzer_183.root","READ");
  Old->cd("Rates/RateEfficiencies/SingleMuIso")  ;
  gDirectory->pwd();
  gDirectory->ReadKeys();
  TH1F *MCTurnOnL1Old= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL1Filtered"); 
  New->cd("Rates/RateEfficiencies/SingleMuIso")  ;
  gDirectory->pwd();
  gDirectory->ReadKeys();
  TH1F *MCTurnOnL1Full= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL1Filtered"); 
  gStyle->SetOptStat(0);
  gStyle->SetPadColor(0);
  gStyle->SetStatColor(0);
  
  if (MCTurnOnL1Old) {
  MCTurnOnL1Old->SetLineColor(2);
  MCTurnOnL1New->SetLineColor(4);
  MCTurnOnL1Old->SetTitle("L1 175");
  MCTurnOnL1Old->GetYaxis()->SetRangeUser(0.,105.);
  MCTurnOnL1Old->GetXaxis()->SetRangeUser(3.,40.);
  MCTurnOnL1Old->SetLineWidth(2);
  MCTurnOnL1New->SetTitle("L1 183");
  MCTurnOnL1Old->Draw();
  MCTurnOnL1New->Draw("same");
  MCTurnOnL1Old->SetDirectory(0);
  MCTurnOnL1New->SetDirectory(0);
  }
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L1FastFull.gif");

  Old->cd("Rates/Distributions/SingleMuIso")  ;
  gDirectory->ls();
  TH1F *MCTurnOnL2Old= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL2PreFiltered"); 

  TH1F *MCTurnOnL2IsoOld= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL2IsoFiltered"); 
  TH1F *MCTurnOnL3Old= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL3PreFiltered"); 
  TH1F *MCTurnOnL3IsoOld= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL3IsoFiltered"); 
  TH1F *MCEtaEffL1Old= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL1Filtered"); 
  TH1F *MCEtaEffL2Old= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL2PreFiltered"); 
  TH1F *MCEtaEffL2IsoOld= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL2IsoFiltered"); 
  TH1F *MCEtaEffL3Old= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL3PreFiltered"); 
  TH1F *MCEtaEffL3IsoOld= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL3IsoFiltered"); 
  TH1F *MCPhiEffL1Old= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL1Filtered"); 
  TH1F *MCPhiEffL2Old= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL2PreFiltered"); 
  TH1F *MCPhiEffL2IsoOld= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL2IsoFiltered"); 
  TH1F *MCPhiEffL3Old= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL3PreFiltered"); 
  TH1F *MCPhiEffL3IsoOld= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL3IsoFiltered"); 
  MCTurnOnL2Old->SetLineWidth(2);
  MCTurnOnL2IsoOld->SetLineWidth(2);
  MCTurnOnL3Old->SetLineWidth(2);
  MCTurnOnL2IsoOld->SetLineWidth(2);
  MCTurnOnL3IsoOld->SetLineWidth(2);
  MCEtaEffL1Old->SetLineWidth(2);
  MCEtaEffL2Old->SetLineWidth(2);
  MCEtaEffL2IsoOld->SetLineWidth(2);
  MCEtaEffL3Old->SetLineWidth(2);
  MCEtaEffL3IsoOld->SetLineWidth(2);
  MCPhiEffL1Old->SetLineWidth(2);
  MCPhiEffL2Old->SetLineWidth(2);
  MCPhiEffL2IsoOld->SetLineWidth(2);
  MCPhiEffL3Old->SetLineWidth(2);
  MCPhiEffL3IsoOld->SetLineWidth(2);
  New->cd("Rates/Distributions/SingleMuIso")  ;
  gDirectory->ls();
  TH1F *MCTurnOnL2Full= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL2PreFiltered"); 
  TH1F *MCTurnOnL2IsoFull= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL2IsoFiltered"); 
  TH1F *MCTurnOnL3Full= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL3PreFiltered"); 
  TH1F *MCTurnOnL3IsoFull= (TH1F *)gDirectory->Get("MCTurnOn_SingleMuIsoL3IsoFiltered"); 
  TH1F *MCEtaEffL1Full= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL1Filtered"); 
  TH1F *MCEtaEffL2Full= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL2PreFiltered"); 
  TH1F *MCEtaEffL2IsoFull= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL2IsoFiltered"); 
  TH1F *MCEtaEffL3Full= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL3PreFiltered"); 
  TH1F *MCEtaEffL3IsoFull= (TH1F *)gDirectory->Get("MCeta_SingleMuIsoL3IsoFiltered"); 
  TH1F *MCPhiEffL1Full= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL1Filtered"); 
  TH1F *MCPhiEffL2Full= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL2PreFiltered"); 
  TH1F *MCPhiEffL2IsoFull= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL2IsoFiltered"); 
  TH1F *MCPhiEffL3Full= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL3PreFiltered"); 
  TH1F *MCPhiEffL3IsoFull= (TH1F *)gDirectory->Get("MCphi_SingleMuIsoL3IsoFiltered"); 
  MCTurnOnL2Old->SetLineColor(2);
  MCTurnOnL2New->SetLineColor(4);
  MCTurnOnL2Old->SetTitle("L2 175");
  MCTurnOnL2Old->GetYaxis()->SetRangeUser(0.,105.);
  MCTurnOnL2Old->GetXaxis()->SetRangeUser(5.,40.);
  MCTurnOnL2Old->SetLineWidth(2);
  MCTurnOnL2New->SetTitle("L2 183");
  MCTurnOnL2Old->Draw();
  MCTurnOnL2New->Draw("same");
  MCTurnOnL2Old->SetDirectory(0);
  MCTurnOnL2New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2FastFull.gif");
  MCTurnOnL2IsoOld->SetLineColor(2);
  MCTurnOnL2IsoNew->SetLineColor(4);
  MCTurnOnL2IsoOld->SetTitle("L2 Iso 175");
  MCTurnOnL2IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  MCTurnOnL2IsoOld->SetLineWidth(2);
  MCTurnOnL2IsoNew->SetTitle("L2 Iso 183");
  MCTurnOnL2IsoOld->Draw();
  MCTurnOnL2IsoNew->Draw("same");
  MCTurnOnL2IsoOld->SetDirectory(0);
  MCTurnOnL2IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2IsoFastFull.gif");
  MCTurnOnL3Old->SetLineColor(2);
  MCTurnOnL3New->SetLineColor(4);
  MCTurnOnL3Old->SetTitle("L3 175");
  MCTurnOnL3Old->GetYaxis()->SetRangeUser(0.,105.);
  MCTurnOnL3Old->GetXaxis()->SetRangeUser(5.,40.);
  MCTurnOnL3Old->SetLineWidth(2);
  MCTurnOnL3New->SetTitle("L3 183");
  MCTurnOnL3Old->Draw();
  MCTurnOnL3New->Draw("same");
  MCTurnOnL3Old->SetDirectory(0);
  MCTurnOnL3New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3FastFull.gif");
  MCTurnOnL3IsoOld->SetLineColor(2);
  MCTurnOnL3IsoNew->SetLineColor(4);
  MCTurnOnL3IsoOld->SetTitle("L3 Iso 175");
  MCTurnOnL3IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  MCTurnOnL3IsoOld->GetXaxis()->SetRangeUser(5.,40.);
  MCTurnOnL3IsoOld->SetLineWidth(2);
  MCTurnOnL3IsoNew->SetTitle("L3 Iso 183");
  MCTurnOnL3IsoOld->Draw();
  MCTurnOnL3IsoNew->Draw("same");
  MCTurnOnL3IsoOld->SetDirectory(0);
  MCTurnOnL3IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3IsoFastFull.gif");


  MCEtaEffL1Old->SetLineColor(2);
  MCEtaEffL1New->SetLineColor(4);
  MCEtaEffL1Old->SetTitle("L1 175");
  MCEtaEffL1Old->GetYaxis()->SetRangeUser(0.,105.);
  MCEtaEffL1Old->GetXaxis()->SetRangeUser(-2.1,2.1);
  MCEtaEffL1Old->GetXaxis()->SetTitle("Eta");
  MCEtaEffL1Old->SetLineWidth(2);
  MCEtaEffL1New->SetTitle("L1 183");
  MCEtaEffL1Old->Draw();
  MCEtaEffL1New->Draw("same");
  MCEtaEffL1Old->SetDirectory(0);
  MCEtaEffL1New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L1FastFullEta.gif");
  MCEtaEffL2Old->SetLineColor(2);
  MCEtaEffL2New->SetLineColor(4);
  MCEtaEffL2Old->SetTitle("L2 175");
  MCEtaEffL2Old->GetYaxis()->SetRangeUser(0.,105.);
  MCEtaEffL2Old->GetXaxis()->SetRangeUser(-2.1,2.1);
  MCEtaEffL2Old->GetXaxis()->SetTitle("Eta");
  MCEtaEffL2Old->SetLineWidth(2);
  MCEtaEffL2New->SetTitle("L2 183");
  MCEtaEffL2Old->Draw();
  MCEtaEffL2New->Draw("same");
  MCEtaEffL2Old->SetDirectory(0);
  MCEtaEffL2New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2FastFullEta.gif");
  MCEtaEffL2IsoOld->SetLineColor(2);
  MCEtaEffL2IsoNew->SetLineColor(4);
  MCEtaEffL2IsoOld->SetTitle("L2 Iso 175");
  MCEtaEffL2IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  MCEtaEffL2IsoOld->GetXaxis()->SetRangeUser(-2.1,2.1);
  MCEtaEffL2IsoOld->GetXaxis()->SetTitle("Eta");
  MCEtaEffL2IsoOld->SetLineWidth(2);
  MCEtaEffL2IsoNew->SetTitle("L2 Iso 183");
  MCEtaEffL2IsoOld->Draw();
  MCEtaEffL2IsoNew->Draw("same");
  MCEtaEffL2IsoOld->SetDirectory(0);
  MCEtaEffL2IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2IsoFastFullEta.gif");
  MCEtaEffL3Old->SetLineColor(2);
  MCEtaEffL3New->SetLineColor(4);
  MCEtaEffL3Old->SetTitle("L3 175");
  MCEtaEffL3Old->GetYaxis()->SetRangeUser(0.,105.);
  MCEtaEffL3Old->GetXaxis()->SetRangeUser(-2.1,2.1);
  MCEtaEffL3Old->GetXaxis()->SetTitle("Eta");
  MCEtaEffL3Old->SetLineWidth(2);
  MCEtaEffL3New->SetTitle("L3 183");
  MCEtaEffL3Old->Draw();
  MCEtaEffL3New->Draw("same");
  MCEtaEffL3Old->SetDirectory(0);
  MCEtaEffL3New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3FastFullEta.gif");
  MCEtaEffL3IsoOld->SetLineColor(2);
  MCEtaEffL3IsoNew->SetLineColor(4);
  MCEtaEffL3IsoOld->SetTitle("L3 Iso 175");
  MCEtaEffL3IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  MCEtaEffL3IsoOld->GetXaxis()->SetRangeUser(-2.1,2.1);
  MCEtaEffL3IsoOld->SetLineWidth(2);
  MCEtaEffL3IsoNew->SetTitle("L3 Iso 183");
  MCEtaEffL3IsoOld->Draw();
  MCEtaEffL3IsoNew->Draw("same");
  MCEtaEffL3IsoOld->SetDirectory(0);
  MCEtaEffL3IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3IsoFastFullEta.gif");

  MCPhiEffL1Old->SetLineColor(2);
  MCPhiEffL1New->SetLineColor(4);
  MCPhiEffL1Old->SetTitle("L1 175");
  MCPhiEffL1Old->GetYaxis()->SetRangeUser(0.,105.);
  MCPhiEffL1Old->SetLineWidth(2);
  MCPhiEffL1New->SetTitle("L1 183");
  MCPhiEffL1Old->Draw();
  MCPhiEffL1New->Draw("same");
  MCPhiEffL1Old->SetDirectory(0);
  MCPhiEffL1New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L1FastFullPhi.gif");

  MCPhiEffL2Old->SetLineColor(2);
  MCPhiEffL2New->SetLineColor(4);
  MCPhiEffL2Old->SetTitle("L2 175");
  MCPhiEffL2Old->GetYaxis()->SetRangeUser(0.,105.);
  MCPhiEffL2Old->SetLineWidth(2);
  MCPhiEffL2New->SetTitle("L2 183");
  MCPhiEffL2Old->Draw();
  MCPhiEffL2New->Draw("same");
  MCPhiEffL2Old->SetDirectory(0);
  MCPhiEffL2New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2FastFullPhi.gif");
  MCPhiEffL2IsoOld->SetLineColor(2);
  MCPhiEffL2IsoNew->SetLineColor(4);
  MCPhiEffL2IsoOld->SetTitle("L2 Iso 175");
  MCPhiEffL2IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  MCPhiEffL2IsoOld->SetLineWidth(2);
  MCPhiEffL2IsoNew->SetTitle("L2 Iso 183");
  MCPhiEffL2IsoOld->Draw();
  MCPhiEffL2IsoNew->Draw("same");
  MCPhiEffL2IsoOld->SetDirectory(0);
  MCPhiEffL2IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2IsoFastFullPhi.gif");
  MCPhiEffL3Old->SetLineColor(2);
  MCPhiEffL3New->SetLineColor(4);
  MCPhiEffL3Old->SetTitle("L3 175");
  MCPhiEffL3Old->GetYaxis()->SetRangeUser(0.,105.);
  MCPhiEffL3Old->SetLineWidth(2);
  MCPhiEffL3New->SetTitle("L3 183");
  MCPhiEffL3Old->Draw();
  MCPhiEffL3New->Draw("same");
  MCPhiEffL3Old->SetDirectory(0);
  MCPhiEffL3New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3FastFullPhi.gif");
  MCPhiEffL3IsoOld->SetLineColor(2);
  MCPhiEffL3IsoNew->SetLineColor(4);
  MCPhiEffL3IsoOld->SetTitle("L3 Iso 175");
  MCPhiEffL3IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  MCPhiEffL3IsoOld->SetLineWidth(2);
  MCPhiEffL3IsoNew->SetTitle("L3 Iso 183");
  MCPhiEffL3IsoOld->Draw();
  MCPhiEffL3IsoNew->Draw("same");
  MCPhiEffL3IsoOld->SetDirectory(0);
  MCPhiEffL3IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3IsoFastFullPhi.gif");

  Old->cd("Rates/RateEfficiencies/SingleMuIso")  ;
  gDirectory->pwd();
  gDirectory->ReadKeys();
  TH1F *RECOTurnOnL1Old= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL1Filtered"); 
  New->cd("Rates/RateEfficiencies/SingleMuIso")  ;
  gDirectory->pwd();
  gDirectory->ReadKeys();
  TH1F *RECOTurnOnL1Full= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL1Filtered"); 
  gStyle->SetOptStat(0);
  gStyle->SetPadColor(0);
  gStyle->SetStatColor(0);
  
  if (RECOTurnOnL1Old) {
  RECOTurnOnL1Old->SetLineColor(2);
  RECOTurnOnL1New->SetLineColor(4);
  RECOTurnOnL1Old->SetTitle("L1 175");
  RECOTurnOnL1Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOTurnOnL1Old->GetXaxis()->SetRangeUser(3.,40.);
  RECOTurnOnL1Old->SetLineWidth(2);
  RECOTurnOnL1New->SetTitle("L1 183");
  RECOTurnOnL1Old->Draw();
  RECOTurnOnL1New->Draw("same");
  RECOTurnOnL1Old->SetDirectory(0);
  RECOTurnOnL1New->SetDirectory(0);
  }
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L1FastFullRECO.gif");

  Old->cd("Rates/Distributions/SingleMuIso")  ;
  gDirectory->ls();
  TH1F *RECOTurnOnL2Old= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL2PreFiltered"); 
  TH1F *RECOTurnOnL2IsoOld= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL2IsoFiltered"); 
  TH1F *RECOTurnOnL3Old= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL3PreFiltered"); 
  TH1F *RECOTurnOnL3IsoOld= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL3IsoFiltered"); 
  TH1F *RECOEtaEffL1Old= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL1Filtered"); 
  TH1F *RECOEtaEffL2Old= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL2PreFiltered"); 
  TH1F *RECOEtaEffL2IsoOld= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL2IsoFiltered"); 
  TH1F *RECOEtaEffL3Old= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL3PreFiltered"); 
  TH1F *RECOEtaEffL3IsoOld= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL3IsoFiltered"); 
  TH1F *RECOPhiEffL1Old= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL1Filtered"); 
  TH1F *RECOPhiEffL2Old= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL2PreFiltered"); 
  TH1F *RECOPhiEffL2IsoOld= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL2IsoFiltered"); 
  TH1F *RECOPhiEffL3Old= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL3PreFiltered"); 
  TH1F *RECOPhiEffL3IsoOld= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL3IsoFiltered"); 

  New->cd("Rates/Distributions/SingleMuIso")  ;
  gDirectory->ls();
  TH1F *RECOTurnOnL2Full= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL2PreFiltered"); 
  TH1F *RECOTurnOnL2IsoFull= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL2IsoFiltered"); 
  TH1F *RECOTurnOnL3Full= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL3PreFiltered"); 
  TH1F *RECOTurnOnL3IsoFull= (TH1F *)gDirectory->Get("RECOTurnOn_SingleMuIsoL3IsoFiltered"); 
  TH1F *RECOEtaEffL1Full= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL1Filtered"); 
  TH1F *RECOEtaEffL2Full= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL2PreFiltered"); 
  TH1F *RECOEtaEffL2IsoFull= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL2IsoFiltered"); 
  TH1F *RECOEtaEffL3Full= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL3PreFiltered"); 
  TH1F *RECOEtaEffL3IsoFull= (TH1F *)gDirectory->Get("RECOeta_SingleMuIsoL3IsoFiltered"); 
  TH1F *RECOPhiEffL1Full= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL1Filtered"); 
  TH1F *RECOPhiEffL2Full= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL2PreFiltered"); 
  TH1F *RECOPhiEffL2IsoFull= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL2IsoFiltered"); 
  TH1F *RECOPhiEffL3Full= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL3PreFiltered"); 
  TH1F *RECOPhiEffL3IsoFull= (TH1F *)gDirectory->Get("RECOphi_SingleMuIsoL3IsoFiltered"); 
  RECOTurnOnL2Old->SetLineColor(2);
  RECOTurnOnL2New->SetLineColor(4);
  RECOTurnOnL2Old->SetTitle("L2 175");
  RECOTurnOnL2Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOTurnOnL2Old->GetXaxis()->SetRangeUser(5.,40.);
  RECOTurnOnL2Old->SetLineWidth(2);
  RECOTurnOnL2New->SetTitle("L2 183");
  RECOTurnOnL2Old->Draw();
  RECOTurnOnL2New->Draw("same");
  RECOTurnOnL2Old->SetDirectory(0);
  RECOTurnOnL2New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2FastFullRECO.gif");
  RECOTurnOnL2IsoOld->SetLineColor(2);
  RECOTurnOnL2IsoNew->SetLineColor(4);
  RECOTurnOnL2IsoOld->SetTitle("L2 Iso 175");
  RECOTurnOnL2IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  RECOTurnOnL2IsoOld->GetXaxis()->SetRangeUser(5.,40.);
  RECOTurnOnL2IsoOld->SetLineWidth(2);
  RECOTurnOnL2IsoNew->SetTitle("L2 Iso 183");
  RECOTurnOnL2IsoOld->Draw();
  RECOTurnOnL2IsoNew->Draw("same");
  RECOTurnOnL2IsoOld->SetDirectory(0);
  RECOTurnOnL2IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2IsoFastFullRECO.gif");
  RECOTurnOnL3Old->SetLineColor(2);
  RECOTurnOnL3New->SetLineColor(4);
  RECOTurnOnL3Old->SetTitle("L3 175");
  RECOTurnOnL3Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOTurnOnL3Old->GetXaxis()->SetRangeUser(5.,40.);
  RECOTurnOnL3Old->SetLineWidth(2);
  RECOTurnOnL3New->SetTitle("L3 183");
  RECOTurnOnL3Old->Draw();
  RECOTurnOnL3New->Draw("same");
  RECOTurnOnL3Old->SetDirectory(0);
  RECOTurnOnL3New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3FastFullRECO.gif");
  RECOTurnOnL3IsoOld->SetLineColor(2);
  RECOTurnOnL3IsoNew->SetLineColor(4);
  RECOTurnOnL3IsoOld->SetTitle("L3 Iso 175");
  RECOTurnOnL3IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  RECOTurnOnL3IsoOld->GetXaxis()->SetRangeUser(5.,40.);
  RECOTurnOnL3IsoOld->SetLineWidth(2);
  RECOTurnOnL3IsoNew->SetTitle("L3 Iso 183");
  RECOTurnOnL3IsoOld->Draw();
  RECOTurnOnL3IsoNew->Draw("same");
  RECOTurnOnL3IsoOld->SetDirectory(0);
  RECOTurnOnL3IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3IsoFastFullRECO.gif");


  RECOEtaEffL1Old->SetLineColor(2);
  RECOEtaEffL1New->SetLineColor(4);
  RECOEtaEffL1Old->SetTitle("L1 175");
  RECOEtaEffL1Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOEtaEffL1Old->GetXaxis()->SetRangeUser(-2.1,2.1);
  RECOEtaEffL1Old->GetXaxis()->SetTitle("Eta");
  RECOEtaEffL1Old->SetLineWidth(2);
  RECOEtaEffL1New->SetTitle("L1 183");
  RECOEtaEffL1Old->Draw();
  RECOEtaEffL1New->Draw("same");
  RECOEtaEffL1Old->SetDirectory(0);
  RECOEtaEffL1New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L1FastFullEtaRECO.gif");
  RECOEtaEffL2Old->SetLineColor(2);
  RECOEtaEffL2New->SetLineColor(4);
  RECOEtaEffL2Old->SetTitle("L2 175");
  RECOEtaEffL2Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOEtaEffL2Old->GetXaxis()->SetTitle("Eta");
  RECOEtaEffL2Old->GetXaxis()->SetRangeUser(-2.1,2.1);
  RECOEtaEffL2Old->SetLineWidth(2);
  RECOEtaEffL2New->SetTitle("L2 183");
  RECOEtaEffL2Old->Draw();
  RECOEtaEffL2New->Draw("same");
  RECOEtaEffL2Old->SetDirectory(0);
  RECOEtaEffL2New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2FastFullEtaRECO.gif");
  RECOEtaEffL2IsoOld->SetLineColor(2);
  RECOEtaEffL2IsoNew->SetLineColor(4);
  RECOEtaEffL2IsoOld->SetTitle("L2 Iso 175");
  RECOEtaEffL2IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  RECOEtaEffL2IsoOld->GetXaxis()->SetTitle("Eta");
  RECOEtaEffL2IsoOld->GetXaxis()->SetRangeUser(-2.1,2.1);
  RECOEtaEffL2IsoOld->SetLineWidth(2);
  RECOEtaEffL2IsoNew->SetTitle("L2 Iso 183");
  RECOEtaEffL2IsoOld->Draw();
  RECOEtaEffL2IsoNew->Draw("same");
  RECOEtaEffL2IsoOld->SetDirectory(0);
  RECOEtaEffL2IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2IsoFastFullEtaRECO.gif");
  RECOEtaEffL3Old->SetLineColor(2);
  RECOEtaEffL3New->SetLineColor(4);
  RECOEtaEffL3Old->SetTitle("L3 175");
  RECOEtaEffL3Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOEtaEffL3Old->GetXaxis()->SetRangeUser(-2.1,2.1);
  RECOEtaEffL3Old->GetXaxis()->SetTitle("Eta");
  RECOEtaEffL3Old->SetLineWidth(2);
  RECOEtaEffL3New->SetTitle("L3 183");
  RECOEtaEffL3Old->Draw();
  RECOEtaEffL3New->Draw("same");
  RECOEtaEffL3Old->SetDirectory(0);
  RECOEtaEffL3New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3FastFullEtaRECO.gif");
  RECOEtaEffL3IsoOld->SetLineColor(2);
  RECOEtaEffL3IsoNew->SetLineColor(4);
  RECOEtaEffL3IsoOld->SetTitle("L3 Iso 175");
  RECOEtaEffL3IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  RECOEtaEffL3IsoOld->GetXaxis()->SetRangeUser(-2.1,2.1);
  RECOEtaEffL3IsoOld->SetLineWidth(2);
  RECOEtaEffL3IsoNew->SetTitle("L3 Iso 183");
  RECOEtaEffL3IsoOld->Draw();
  RECOEtaEffL3IsoNew->Draw("same");
  RECOEtaEffL3IsoOld->SetDirectory(0);
  RECOEtaEffL3IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3IsoFastFullEtaRECO.gif");

  RECOPhiEffL1Old->SetLineColor(2);
  RECOPhiEffL1New->SetLineColor(4);
  RECOPhiEffL1Old->SetTitle("L1 175");
  RECOPhiEffL1Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOPhiEffL1Old->SetLineWidth(2);
  RECOPhiEffL1New->SetTitle("L1 183");
  RECOPhiEffL1Old->Draw();
  RECOPhiEffL1New->Draw("same");
  RECOPhiEffL1Old->SetDirectory(0);
  RECOPhiEffL1New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L1FastFullPhiRECO.gif");

  RECOPhiEffL2Old->SetLineColor(2);
  RECOPhiEffL2New->SetLineColor(4);
  RECOPhiEffL2Old->SetTitle("L2 175");
  RECOPhiEffL2Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOPhiEffL2Old->SetLineWidth(2);
  RECOPhiEffL2New->SetTitle("L2 183");
  RECOPhiEffL2Old->Draw();
  RECOPhiEffL2New->Draw("same");
  RECOPhiEffL2Old->SetDirectory(0);
  RECOPhiEffL2New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2FastFullPhiRECO.gif");
  RECOPhiEffL2IsoOld->SetLineColor(2);
  RECOPhiEffL2IsoNew->SetLineColor(4);
  RECOPhiEffL2IsoOld->SetTitle("L2 Iso 175");
  RECOPhiEffL2IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  RECOPhiEffL2IsoOld->SetLineWidth(2);
  RECOPhiEffL2IsoNew->SetTitle("L2 Iso 183");
  RECOPhiEffL2IsoOld->Draw();
  RECOPhiEffL2IsoNew->Draw("same");
  RECOPhiEffL2IsoOld->SetDirectory(0);
  RECOPhiEffL2IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L2IsoFastFullPhiRECO.gif");
  RECOPhiEffL3Old->SetLineColor(2);
  RECOPhiEffL3New->SetLineColor(4);
  RECOPhiEffL3Old->SetTitle("L3 175");
  RECOPhiEffL3Old->GetYaxis()->SetRangeUser(0.,105.);
  RECOPhiEffL3Old->SetLineWidth(2);
  RECOPhiEffL3New->SetTitle("L3 183");
  RECOPhiEffL3Old->Draw();
  RECOPhiEffL3New->Draw("same");
  RECOPhiEffL3Old->SetDirectory(0);
  RECOPhiEffL3New->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3FastFullPhiRECO.gif");
  RECOPhiEffL3IsoOld->SetLineColor(2);
  RECOPhiEffL3IsoNew->SetLineColor(4);
  RECOPhiEffL3IsoOld->SetTitle("L3 Iso 175");
  RECOPhiEffL3IsoOld->GetYaxis()->SetRangeUser(0.,105.);
  RECOPhiEffL3IsoOld->SetLineWidth(2);
  RECOPhiEffL3IsoNew->SetTitle("L3 Iso 183");
  RECOPhiEffL3IsoOld->Draw();
  RECOPhiEffL3IsoNew->Draw("same");
  RECOPhiEffL3IsoOld->SetDirectory(0);
  RECOPhiEffL3IsoNew->SetDirectory(0);
  gPad->BuildLegend(0.55,0.15,0.85,0.3);
  gPad->Update();
  c1->SaveAs("L3IsoFastFullPhiRECO.gif");

  //  Old->Close();
  //New->Close();
}


